### ISSUE TITLE
Example in README doesn't work

### ISSUE THREAD

**Issue by xd009642** [rust-cv/hnsw#21]
`HNSW` was renamed to `Hnsw` in version 0.7 so the readme is out of date in that respect. Also I went to the docs looking for recommended values for M and M0 as these values now need to be set, but don't see any relevant documentation for them. I guess I should look to the original paper, although it would be better if it was mentioned within the crate docs

**Comment by vadixidav** [comment]
I updated the README so that the examples are up-to-date. I also left a tip in there at the top specifically for the M and M0 values.
