### ISSUE TITLE
search_layer and search_zero_layer have code duplication

### ISSUE THREAD

**Issue by vadixidav** [rust-cv/hnsw#3]
I was unable to easily solve the code duplication between these two methods. It is possible to do so with [generic associated types](https://github.com/rust-lang/rust/issues/44265) (GATs), but even when enabling the nightly feature, I was unable to get it to work, as the feature is fairly unstable currently. Once this feature or some other method of implementing this with zero-cost abstractions becomes possible, I will do so. Until then, these two methods will violate the DRY principle.

**Comment by xd009642** [comment]
Fixed in #28
